#!/usr/bin/env bun
// e2e-test.ts — End-to-end test for the capture-plan hook lifecycle
// Exercises: SessionStart → capture-plan (ExitPlanMode) → capture-done (Stop) → journal
// Uses real Obsidian CLI and vault; synthetic transcript and payloads.

import {
  existsSync,
  mkdirSync,
  readdirSync,
  readFileSync,
  rmSync,
  unlinkSync,
  writeFileSync,
} from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { contextHintPath } from "./capture-session-start.ts";
import {
  createVaultNote,
  getDateParts,
  getJournalPath,
  getVaultPath,
  loadConfig,
  nextCounter,
  padCounter,
  shortSessionId,
  toSlug,
} from "./shared.ts";

// ---- CLI ----

const skipClean = process.argv.includes("--skip-clean");

// ---- Types ----

interface CheckResult {
  seq: number;
  phase: string;
  check: string;
  pass: boolean;
  detail: string;
}

// ---- Test State ----

const results: CheckResult[] = [];
let seq = 0;

function record(phase: string, check: string, pass: boolean, detail = ""): void {
  seq++;
  results.push({ seq, phase, check, pass, detail });
  const mark = pass ? "✓" : "✗";
  const detailStr = detail ? ` (${detail})` : "";
  console.log(`  ${mark} ${check}${detailStr}`);
}

// ---- Synthetic Data ----

const PLAN_TITLE = "E2E Test Synthetic Widget";
const PLAN_CONTENT = `# ${PLAN_TITLE}

## Context

This is a synthetic plan generated by the e2e test suite to validate the full capture-plan hook lifecycle.

## Steps

1. Create a new widget component in \`/src/widget.ts\`
2. Add unit tests in \`/src/widget.test.ts\`
3. Wire up the widget in the main application entry point
4. Run all tests to verify nothing is broken

## Verification

Run \`bun test\` and confirm all tests pass.
`;

const LAST_ASSISTANT_MESSAGE =
  "Implementation complete. Created widget.ts with the new component and wired it into the main application. All tests pass — the e2e test validates the full capture-plan lifecycle end-to-end.";

function buildTranscript(_sessionId: string, planContent: string): string {
  const now = Date.now();
  const ts = (offsetMs: number) => new Date(now - offsetMs).toISOString();

  const entries = [
    // Planning phase
    {
      type: "human",
      timestamp: ts(300_000),
      message: {
        role: "user",
        content: "Build an e2e test widget for the capture-plan plugin",
      },
    },
    {
      type: "assistant",
      timestamp: ts(290_000),
      model: "claude-sonnet-4-20250514",
      message: {
        role: "assistant",
        content: [{ type: "text", text: "I'll plan this implementation for the e2e test widget." }],
        usage: {
          input_tokens: 1200,
          output_tokens: 400,
          cache_read_input_tokens: 800,
          cache_creation_input_tokens: 0,
        },
      },
    },
    {
      type: "assistant",
      timestamp: ts(270_000),
      model: "claude-sonnet-4-20250514",
      message: {
        role: "assistant",
        content: [
          { type: "text", text: "Let me read the existing code structure first." },
          {
            type: "tool_use",
            name: "Read",
            id: "tu_read_1",
            input: { file_path: "/src/app.ts" },
          },
        ],
        usage: {
          input_tokens: 1500,
          output_tokens: 300,
          cache_read_input_tokens: 1000,
          cache_creation_input_tokens: 0,
        },
      },
    },
    {
      type: "human",
      timestamp: ts(265_000),
      message: {
        role: "user",
        content: [
          {
            type: "tool_result",
            tool_use_id: "tu_read_1",
            content: 'export function main() { console.log("app"); }',
          },
        ],
      },
    },
    {
      type: "assistant",
      timestamp: ts(250_000),
      model: "claude-sonnet-4-20250514",
      message: {
        role: "assistant",
        content: [
          {
            type: "tool_use",
            name: "ExitPlanMode",
            id: "tu_exit_plan",
            input: { plan: planContent },
          },
        ],
        usage: {
          input_tokens: 2000,
          output_tokens: 600,
          cache_read_input_tokens: 1200,
          cache_creation_input_tokens: 0,
        },
      },
    },
    // Execution phase
    {
      type: "human",
      timestamp: ts(245_000),
      message: {
        role: "user",
        content: [
          {
            type: "tool_result",
            tool_use_id: "tu_exit_plan",
            content: "Plan approved. Proceeding with implementation.",
          },
        ],
      },
    },
    {
      type: "assistant",
      timestamp: ts(200_000),
      model: "claude-sonnet-4-20250514",
      message: {
        role: "assistant",
        content: [
          { type: "text", text: "Now implementing the widget component." },
          {
            type: "tool_use",
            name: "Edit",
            id: "tu_edit_1",
            input: {
              file_path: "/src/widget.ts",
              old_string: "",
              new_string: 'export function widget() { return "widget"; }',
            },
          },
        ],
        usage: {
          input_tokens: 2500,
          output_tokens: 500,
          cache_read_input_tokens: 1500,
          cache_creation_input_tokens: 0,
        },
      },
    },
    {
      type: "human",
      timestamp: ts(195_000),
      message: {
        role: "user",
        content: [
          { type: "tool_result", tool_use_id: "tu_edit_1", content: "File edited successfully." },
        ],
      },
    },
    // Agent tool — tests agent prompt file extraction
    {
      type: "assistant",
      timestamp: ts(192_000),
      model: "claude-sonnet-4-20250514",
      message: {
        role: "assistant",
        content: [
          {
            type: "tool_use",
            name: "Agent",
            id: "tu_agent_1",
            input: {
              subagent_type: "Explore",
              description: "Verify widget integration",
              prompt:
                "# Widget Integration Check\n\nVerify that the widget component is properly integrated:\n\n1. Check imports in app.ts\n2. Confirm widget function is exported\n3. Look for test coverage",
            },
          },
        ],
        usage: {
          input_tokens: 2800,
          output_tokens: 150,
          cache_read_input_tokens: 1800,
          cache_creation_input_tokens: 0,
        },
      },
    },
    {
      type: "human",
      timestamp: ts(185_000),
      message: {
        role: "user",
        content: [
          {
            type: "tool_result",
            tool_use_id: "tu_agent_1",
            content: "Widget integration verified. All imports and exports are correct.",
          },
        ],
      },
    },
    {
      type: "assistant",
      timestamp: ts(150_000),
      model: "claude-sonnet-4-20250514",
      message: {
        role: "assistant",
        content: [
          {
            type: "tool_use",
            name: "Bash",
            id: "tu_bash_1",
            input: { command: "bun test" },
          },
        ],
        usage: {
          input_tokens: 3000,
          output_tokens: 200,
          cache_read_input_tokens: 2000,
          cache_creation_input_tokens: 0,
        },
      },
    },
    {
      type: "human",
      timestamp: ts(140_000),
      message: {
        role: "user",
        content: [
          { type: "tool_result", tool_use_id: "tu_bash_1", content: "All 200 tests passed." },
        ],
      },
    },
    {
      type: "assistant",
      timestamp: ts(60_000),
      model: "claude-sonnet-4-20250514",
      message: {
        role: "assistant",
        content: [{ type: "text", text: LAST_ASSISTANT_MESSAGE }],
        usage: {
          input_tokens: 3500,
          output_tokens: 300,
          cache_read_input_tokens: 2500,
          cache_creation_input_tokens: 0,
        },
      },
    },
  ];

  return entries.map((e) => JSON.stringify(e)).join("\n") + "\n";
}

// ---- Hook Runner ----

function runHook(
  scriptName: string,
  payload: Record<string, unknown>,
): { exitCode: number; stdout: string; stderr: string } {
  const scriptPath = join(import.meta.dir, scriptName);
  const input = JSON.stringify(payload);
  const result = Bun.spawnSync(["bun", scriptPath], {
    stdin: new Blob([input]),
    stdout: "pipe",
    stderr: "pipe",
  });
  return {
    exitCode: result.exitCode,
    stdout: result.stdout.toString(),
    stderr: result.stderr.toString(),
  };
}

// ---- Journal Cleanup ----

function removeJournalSection(title: string, journalFilePath: string): boolean {
  try {
    let content = readFileSync(journalFilePath, "utf8");
    const header = `### ${title}`;
    let removed = false;

    // Remove all matching sections (handles multiple e2e runs)
    while (content.includes(header)) {
      const lines = content.split("\n");
      let startIdx = -1;
      for (let i = 0; i < lines.length; i++) {
        if (lines[i].trim() === header) {
          startIdx = i > 0 && lines[i - 1].trim() === "" ? i - 1 : i;
          break;
        }
      }
      if (startIdx === -1) break;

      let endIdx = lines.length;
      for (let i = startIdx + 1; i < lines.length; i++) {
        if (/^###?\s/.test(lines[i])) {
          endIdx = i;
          break;
        }
      }
      while (endIdx < lines.length && lines[endIdx]?.trim() === "") {
        endIdx++;
      }

      lines.splice(startIdx, endIdx - startIdx);
      content = lines.join("\n");
      removed = true;
    }

    if (removed) writeFileSync(journalFilePath, content);
    return removed;
  } catch {
    return false;
  }
}

// ---- Test Log ----

function writeTestLog(
  results: CheckResult[],
  planDir: string,
  journalPath: string,
  datetime: string,
  sessionId: string,
  vault?: string,
): boolean {
  const passed = results.filter((r) => r.pass).length;
  const total = results.length;
  const allPass = passed === total;
  const resultStr = allPass ? "pass" : "fail";

  const rows = results.map((r) => {
    const mark = r.pass ? "PASS" : "**FAIL**";
    const detail = r.detail.replace(/\|/g, "\\|").replace(/\n/g, " ");
    return `| ${r.seq} | ${r.phase} | ${r.check} | ${mark} | ${detail} |`;
  });

  const content = `---
created: "[[${journalPath}|${datetime}]]"
type: e2e-test
session: "${shortSessionId(sessionId)}"
result: "${resultStr}"
---
# E2E Test Log

| # | Phase | Check | Result | Detail |
|---|-------|-------|--------|--------|
${rows.join("\n")}

**Result: ${passed}/${total} passed${allPass ? "" : `, ${total - passed} failed`}**
`;

  return createVaultNote(`${planDir}/test-log`, content, vault).success;
}

// ---- Main ----

async function main(): Promise<void> {
  console.log("capture-plan e2e test");
  console.log("=====================\n");

  // ---- Phase 0: Setup ----
  console.log("Preflight");

  // Check obsidian CLI
  const obsCheck = Bun.spawnSync(["which", "obsidian"], { stdout: "pipe", stderr: "pipe" });
  const obsAvailable = obsCheck.exitCode === 0;
  record("preflight", "obsidian CLI available", obsAvailable);
  if (!obsAvailable) {
    console.log("\nFatal: obsidian CLI not found. Install it to run the e2e test.");
    process.exit(1);
  }

  // Load config
  const config = await loadConfig();
  record(
    "preflight",
    "config loaded",
    true,
    `plan_path=${config.plan_path}, journal_path=${config.journal_path}`,
  );

  // Check vault
  const vaultPath = getVaultPath(config.vault);
  const vaultOk = vaultPath !== null;
  record(
    "preflight",
    "vault accessible",
    vaultOk,
    vaultOk ? `${config.vault} → ${vaultPath}` : "getVaultPath returned null",
  );
  if (!vaultPath) {
    console.log("\nFatal: cannot resolve vault path. Check your config and Obsidian CLI.");
    process.exit(1);
  }

  // Generate IDs and paths
  const sessionId = crypto.randomUUID();
  const { dd, mm, yyyy, datetime } = getDateParts();
  const dateDirRelative = `${config.plan_path}/${yyyy}/${mm}-${dd}`;
  const dateDirAbsolute = join(vaultPath, dateDirRelative);
  const counter = nextCounter(dateDirAbsolute);
  const slug = toSlug(PLAN_TITLE);
  const planDir = `${dateDirRelative}/${padCounter(counter)}-${slug}`;
  const planDirAbsolute = join(vaultPath, planDir);
  const journalPath = getJournalPath(config);

  // Create temp cwd for the hooks
  const tempCwd = join(tmpdir(), `e2e-test-cwd-${sessionId.slice(0, 8)}`);
  mkdirSync(tempCwd, { recursive: true });

  // Write synthetic transcript at the path findTranscriptPath() will discover
  // (based on cwd slug: ~/.claude/projects/-<cwd-with-slashes-replaced>/<sessionId>.jsonl)
  const cwdSlug = `-${tempCwd.replace(/\//g, "-")}`;
  const projectDir = join(process.env.HOME || "", ".claude", "projects", cwdSlug);
  mkdirSync(projectDir, { recursive: true });
  const transcriptPath = join(projectDir, `${sessionId}.jsonl`);
  writeFileSync(transcriptPath, buildTranscript(sessionId, PLAN_CONTENT));

  console.log("");

  // ---- Phase 1: SessionStart ----
  console.log("SessionStart hook");
  const sessionStartPayload = {
    session_id: sessionId,
    hook_event_name: "SessionStart",
    model: "claude-sonnet-4-20250514[200k]",
    cwd: tempCwd,
  };
  const ssResult = runHook("capture-session-start.ts", sessionStartPayload);
  const hintFile = contextHintPath(sessionId);
  const hintCreated = existsSync(hintFile);
  record(
    "session-start",
    "context hint created",
    hintCreated,
    hintCreated ? hintFile : `exit=${ssResult.exitCode}`,
  );
  console.log("");

  // ---- Phase 2: capture-plan ----
  console.log("capture-plan hook");
  const planPayload = {
    session_id: sessionId,
    hook_event_name: "PostToolUse",
    tool_name: "ExitPlanMode",
    cwd: tempCwd,
    tool_input: {},
    tool_response: { plan: PLAN_CONTENT },
  };
  const cpResult = runHook("capture-plan.ts", planPayload);
  record(
    "capture-plan",
    "hook exited cleanly",
    cpResult.exitCode === 0,
    `exit=${cpResult.exitCode}`,
  );

  // Validate plan.md
  const planFile = join(planDirAbsolute, "plan.md");
  const planExists = existsSync(planFile);
  record(
    "capture-plan",
    "plan.md exists",
    planExists,
    planExists ? planFile : "not found at predicted path",
  );

  let planContent = "";
  if (planExists) {
    planContent = readFileSync(planFile, "utf8");
    const hasFrontmatter = /^---\n[\s\S]+?\n---/.test(planContent);
    record("capture-plan", "plan.md has frontmatter", hasFrontmatter);
    record("capture-plan", "plan.md has created field", planContent.includes("created:"));
    record("capture-plan", "plan.md has session field", planContent.includes("session:"));
    record("capture-plan", "plan.md has title heading", planContent.includes(`# ${PLAN_TITLE}`));
    record(
      "capture-plan",
      "plan.md has plan body",
      planContent.includes("synthetic plan generated by the e2e test"),
    );
  }

  // Validate state.md (intermediate — should exist before capture-done)
  const stateFile = join(planDirAbsolute, "state.md");
  const stateExists = existsSync(stateFile);
  record("capture-plan", "state.md exists (intermediate)", stateExists);
  console.log("");

  // ---- Phase 3: capture-done ----
  console.log("capture-done hook");
  const stopPayload = {
    session_id: sessionId,
    hook_event_name: "Stop",
    cwd: tempCwd,
    transcript_path: transcriptPath,
    last_assistant_message: LAST_ASSISTANT_MESSAGE,
  };
  const cdResult = runHook("capture-done.ts", stopPayload);
  record(
    "capture-done",
    "hook exited cleanly",
    cdResult.exitCode === 0,
    `exit=${cdResult.exitCode}`,
  );

  // Validate summary.md
  const summaryFile = join(planDirAbsolute, "summary.md");
  const summaryExists = existsSync(summaryFile);
  record("capture-done", "summary.md exists", summaryExists);

  if (summaryExists) {
    const summaryContent = readFileSync(summaryFile, "utf8");
    record("capture-done", "summary.md has plan link", summaryContent.includes("plan:"));
    record("capture-done", "summary.md has duration", summaryContent.includes("duration:"));
    record("capture-done", "summary.md has Summary section", summaryContent.includes("## Summary"));
    record(
      "capture-done",
      "summary.md has Files Changed",
      summaryContent.includes("## Files Changed"),
    );
    record("capture-done", "summary.md lists widget.ts", summaryContent.includes("widget.ts"));
  }

  // Validate tools-stats.md
  const toolsStatsFile = join(planDirAbsolute, "tools-stats.md");
  const toolsStatsExists = existsSync(toolsStatsFile);
  record("capture-done", "tools-stats.md exists", toolsStatsExists);

  if (toolsStatsExists) {
    const statsContent = readFileSync(toolsStatsFile, "utf8");
    record(
      "capture-done",
      "tools-stats has Planning Phase",
      statsContent.includes("## Planning Phase"),
    );
    record(
      "capture-done",
      "tools-stats has Execution Phase",
      statsContent.includes("## Execution Phase"),
    );
    record("capture-done", "tools-stats has Combined", statsContent.includes("## Combined"));
  }

  // Validate tools-log.md
  const toolsLogFile = join(planDirAbsolute, "tools-log.md");
  const toolsLogExists = existsSync(toolsLogFile);
  record("capture-done", "tools-log.md exists", toolsLogExists);

  let logContent = "";
  if (toolsLogExists) {
    logContent = readFileSync(toolsLogFile, "utf8");
    record("capture-done", "tools-log has turns", logContent.includes("### Turn 1"));
  }

  // Validate agent prompt files
  const agentsDir = join(planDirAbsolute, "agents");
  const agentsDirExists = existsSync(agentsDir);
  record("capture-done", "agents/ directory exists", agentsDirExists);

  if (agentsDirExists) {
    const agentFiles = readdirSync(agentsDir).filter((f) => f.endsWith(".md"));
    record(
      "capture-done",
      "agent prompt file exists",
      agentFiles.length > 0,
      agentFiles.length > 0 ? agentFiles[0] : "no .md files in agents/",
    );

    if (agentFiles.length > 0) {
      const agentContent = readFileSync(join(agentsDir, agentFiles[0]), "utf8");
      record(
        "capture-done",
        "agent file has prompt content",
        agentContent.includes("Widget Integration Check"),
      );
    }
  }

  if (toolsLogExists) {
    record(
      "capture-done",
      "tools-log has agent wikilink",
      logContent.includes("agents/") && logContent.includes("Verify widget integration"),
    );
  }

  // Validate state.md cleaned up
  const stateCleanedUp = !existsSync(stateFile);
  record("capture-done", "state.md cleaned up", stateCleanedUp);
  console.log("");

  // Validate journal
  console.log("Journal");
  const journalFile = join(
    vaultPath,
    journalPath.endsWith(".md") ? journalPath : `${journalPath}.md`,
  );
  const journalExists = existsSync(journalFile);
  record("journal", "journal file exists", journalExists, journalFile);

  if (journalExists) {
    const journalContent = readFileSync(journalFile, "utf8");
    const hasSection = journalContent.includes(`### ${PLAN_TITLE}`);
    record("journal", "has plan section", hasSection);

    // Count table rows in the plan section
    if (hasSection) {
      const sectionStart = journalContent.indexOf(`### ${PLAN_TITLE}`);
      const sectionEnd = journalContent.indexOf("\n### ", sectionStart + 1);
      const section =
        sectionEnd > -1
          ? journalContent.slice(sectionStart, sectionEnd)
          : journalContent.slice(sectionStart);
      const tableRows = section
        .split("\n")
        .filter((l) => l.trim().startsWith("|") && !l.trim().startsWith("|---")).length;
      record(
        "journal",
        "has table rows",
        tableRows >= 2,
        `found ${tableRows} rows (expect ≥2: header + plan + summary)`,
      );
    }
  }
  console.log("");

  // ---- Phase 5: Write test log to vault ----
  console.log("Test log");
  const logWritten = writeTestLog(results, planDir, journalPath, datetime, sessionId, config.vault);
  record("test-log", "test-log.md written to vault", logWritten, `${planDir}/test-log.md`);
  console.log("");

  // ---- Phase 6: Cleanup ----
  if (skipClean) {
    console.log("Cleanup: skipped (--skip-clean)");
    console.log(`  Test artifacts preserved at: ${planDir}/`);
    console.log(
      "  Browse in Obsidian: plan.md, summary.md, tools-stats.md, tools-log.md, agents/, test-log.md",
    );
  } else {
    console.log("Cleanup");

    // Remove plan directory from vault
    if (existsSync(planDirAbsolute)) {
      rmSync(planDirAbsolute, { recursive: true });
      record("cleanup", "plan directory removed", !existsSync(planDirAbsolute));
    }

    // Remove journal section
    if (journalExists) {
      const removed = removeJournalSection(PLAN_TITLE, journalFile);
      record("cleanup", "journal section removed", removed);
    }

    // Remove temp files
    try {
      unlinkSync(transcriptPath);
    } catch {
      /* */
    }
    try {
      rmSync(projectDir, { recursive: true });
    } catch {
      /* */
    }
    try {
      unlinkSync(hintFile);
    } catch {
      /* */
    }
    try {
      rmSync(tempCwd, { recursive: true });
    } catch {
      /* */
    }
    record("cleanup", "temp files removed", true);
  }

  // ---- Summary ----
  // Recount after cleanup results
  const finalPassed = results.filter((r) => r.pass).length;
  const finalTotal = results.length;
  const finalAllPass = finalPassed === finalTotal;

  console.log(
    `\nResult: ${finalPassed}/${finalTotal} passed${finalAllPass ? "" : ` (${finalTotal - finalPassed} failed)`}`,
  );
  process.exit(finalAllPass ? 0 : 1);
}

main();
